### ISSUE TITLE
Application crashed after call TinkoffAcquiringSdk#openGooglePay

### ISSUE THREAD

**Issue by baihu92** [nk2IsHere/tinkoff_acquiring_sdk_flutter#4]
Привет

Крашится приложение после вызова TinkoffAcquiringSdk#openGooglePay.

Log:

```2021-01-11 02:39:51.831 8364-8519/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: _, PID: 8364
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-1
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:779)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:144)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
        at eu.nk2.tinkoff_acquiring_sdk.TinkoffBindingsKt$safe$1.invokeSuspend(TinkoffBindings.kt:18)
        at eu.nk2.tinkoff_acquiring_sdk.TinkoffBindingsKt$safe$1.invoke(Unknown Source:24)
        at eu.nk2.tinkoff_acquiring_sdk.TinkoffAcquiringSdkPlugin$onMethodCall$1.invokeSuspend(TinkoffAcquiringSdkPlugin.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by baihu92** [comment]
Краш происходит, если не передавать darkThemeMode. 
Т.к. в таком случае [здесь](https://github.com/nk2IsHere/tinkoff_acquiring_sdk_flutter/blob/00d40c95e42ef0b13f170360886ce7f53e4072f9/lib/tinkoff_acquiring_sdk.dart#L247) будет передаваться строка "null", а затем [здесь](https://github.com/nk2IsHere/tinkoff_acquiring_sdk_flutter/blob/00d40c95e42ef0b13f170360886ce7f53e4072f9/android/src/main/kotlin/eu/nk2/tinkoff_acquiring_sdk/TinkoffProtocol.kt#L78) не найдется такого значения, и будет выбрашено  исключение IllegalArgumentException

**Comment by nk2IsHere** [comment]
Починил в `1.0.3`

**Comment by Mozyra** [comment]
> Привет
> 
> Крашится приложение после вызова TinkoffAcquiringSdk#openGooglePay.
> 
> Log:
> 
> ```
>     Process: _, PID: 8364
>     java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-1
>         at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
>         at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:779)
>         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:144)
>         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
>         at eu.nk2.tinkoff_acquiring_sdk.TinkoffBindingsKt$safe$1.invokeSuspend(TinkoffBindings.kt:18)
>         at eu.nk2.tinkoff_acquiring_sdk.TinkoffBindingsKt$safe$1.invoke(Unknown Source:24)
>         at eu.nk2.tinkoff_acquiring_sdk.TinkoffAcquiringSdkPlugin$onMethodCall$1.invokeSuspend(TinkoffAcquiringSdkPlugin.kt:43)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```

Аналогичная ошибка при вызове `openPaymentScreen`. Версия `1.0.3`

**Comment by mozerrr** [comment]
> Краш происходит, если не передавать darkThemeMode.
> Т.к. в таком случае [здесь](https://github.com/nk2IsHere/tinkoff_acquiring_sdk_flutter/blob/00d40c95e42ef0b13f170360886ce7f53e4072f9/lib/tinkoff_acquiring_sdk.dart#L247) будет передаваться строка "null", а затем [здесь](https://github.com/nk2IsHere/tinkoff_acquiring_sdk_flutter/blob/00d40c95e42ef0b13f170360886ce7f53e4072f9/android/src/main/kotlin/eu/nk2/tinkoff_acquiring_sdk/TinkoffProtocol.kt#L78) не найдется такого значения, и будет выбрашено исключение IllegalArgumentException

Если отправить какие-то неверные данные, то тоже будет краш, надо добавить какие-нибудь проверки.
